# Generated by Django 4.2.20 on 2025-05-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Полное описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('capsule_type', models.CharField(choices=[('electronic', 'electronic'), ('physical', 'physical')], default='electronic', max_length=20, verbose_name='Тип капсулы')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб.)')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка (%)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('availability', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20, verbose_name='Доступность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='capsule.category', verbose_name='Категория')),
                ('description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capsule', to='capsule.capsuledescription', verbose_name='Полное описание')),
                ('tags', models.ManyToManyField(blank=True, related_name='capsules', to='capsule.tag', verbose_name='Теги')),
            ],
        ),
    ]
