# Generated by Django 4.2.20 on 2025-05-29 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
