# Generated by Django 4.2.20 on 2025-05-29 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_capsule_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capsule',
            options={'verbose_name': 'Капсула', 'verbose_name_plural': 'Капсулы'},
        ),
        migrations.AlterModelOptions(
            name='capsuledescription',
            options={'verbose_name': 'Описание капсулы', 'verbose_name_plural': 'Описания капсул'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='capsule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
