# Generated by Django 4.2.20 on 2025-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0003_alter_capsule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='capsule_type',
        ),
        migrations.AddField(
            model_name='category',
            name='availability',
            field=models.CharField(choices=[('available', 'В наличии'), ('unavailable', 'Нет в наличии')], default='available', max_length=20, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='availability',
            field=models.CharField(choices=[('available', 'В наличии'), ('unavailable', 'Нет в наличии')], default='available', max_length=20, verbose_name='Доступность'),
        ),
    ]
