# Generated by Django 4.2.20 on 2025-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0004_remove_category_capsule_type_category_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='availability',
        ),
        migrations.AddField(
            model_name='category',
            name='capsule_type',
            field=models.CharField(choices=[('electronic', 'electronic'), ('physical', 'physical')], default='electronic', max_length=20, verbose_name='Тип капсулы'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20, verbose_name='Доступность'),
        ),
    ]
