# Generated by Django 4.2.20 on 2025-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0005_remove_category_availability_category_capsule_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='availability',
            field=models.CharField(choices=[('available', 'В наличии'), ('unavailable', 'Не в наличии')], default='available', max_length=20, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='category',
            name='capsule_type',
            field=models.CharField(choices=[('electronic', 'Электронные'), ('physical', 'Физические')], default='electronic', max_length=20, verbose_name='Тип капсулы'),
        ),
    ]
