# Generated by Django 4.2.20 on 2025-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0006_alter_capsule_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='capsules/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='capsules/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
