# Generated by Django 4.2.20 on 2025-05-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0007_timecapsule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeCapsule',
        ),
    ]
