# Generated by Django 4.2.20 on 2025-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='capsule_files/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='review_files/'),
        ),
    ]
